apiVersion: apps/v1
kind: Deployment
metadata:
  name: throttlex-nginx
  labels:
    app: throttlex-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: throttlex-nginx
  template:
    metadata:
      labels:
        app: throttlex-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: throttlex-nginx-config
