apiVersion: v1
kind: Service
metadata:
  name: throttlex-nginx
  labels:
    app: throttlex-nginx
spec:
  selector:
    app: throttlex-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
