apiVersion: v1
kind: Service
metadata:
  name: throttlex-postgres
  labels:
    app: throttlex-postgres
spec:
  selector:
    app: throttlex-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
